name: Publish PyPi Fields extension

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'manifest.json'
      - '.github/workflows/publish.yaml'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "web-ext build"
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        filename: "{name}-{version}.xpi"
        ignoreFiles: '[ "package.json","package-lock.json","yarn.lock" ]'

    - name: "Upload Artifact"
      uses: actions/upload-artifact@v4
      with:
        name: target.xpi
        path: ${{ steps.web-ext-build.outputs.target }}
    - name: "Collect sources"
      run: git archive --format=zip --output=sources.zip ${{ github.ref }}
    - name: "Collect metadata"
      id: metadata
      run: echo "json=$(jq -c . < amo_metadata.json)" >> $GITHUB_OUTPUT

  
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - name: "web-ext sign AMO"
      id: web-ext-sign
      uses: kewisch/action-web-ext@v1
      with:
        cmd: sign
        source: ${{ steps.web-ext-build.outputs.target }}
        metaDataFile: amo_metadata.json
        approvalNotes: "Please find more information at https://github.com/hazel-noack/pypi-fields-extention"
        releaseNotes: "Release for version ${{ steps.version.outputs.version }}"
        license: GPL-3.0
        licenseFile: LICENSE.md
        apiKey: ${{ secrets.FIREFOX_API_KEY }}
        apiSecret: ${{ secrets.FIREFOX_CLIENT_SECRET }}
        timeout: 900000

    - name: "Attach release assets to release"
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} \
          ${{ steps.web-ext-sign.outputs.target }}
