name: Publish PyPi Fields extension

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'manifest.json'

jobs:
  Firefox:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Needed for automatic release notes

    - name: Build Extension for Firefox
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build

    - name: 'Sign & publish'
      id: web-ext-sign
      uses: kewisch/action-web-ext@v1
      with:
        cmd: sign
        channel: listed
        source: ${{ steps.web-ext-build.outputs.target }}
        apiKey: ${{ secrets.FIREFOX_API_KEY }}
        apiSecret: ${{ secrets.FIREFOX_CLIENT_SECRET }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 'Firefox Artifacts'
        path: ${{ steps.web-ext-sign.outputs.target }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: ${{ steps.web-ext-sign.outputs.target }}/*
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automatic release for Firefox extension
          - Build number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
          - Triggered by: ${{ github.actor }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}