name: Publish PyPi Fields extension

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: "Build and Release"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "web-ext build"
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        filename: "{name}-{version}.xpi"
        ignoreFiles: '[ "package.json","package-lock.json","yarn.lock" ]'

    - name: "Collect sources"
      run: git archive --format=zip --output=sources.zip ${{ github.ref }}

    - name: "Collect metadata"
      id: metadata
      run: echo "json=$(jq -c . < amo_metadata.json)" >> $GITHUB_OUTPUT

    - name: "Upload Artifact"
      uses: actions/upload-artifact@v4
      with:
        name: 'Build Artifacts'
        path: |
          ${{ steps.web-ext-build.outputs.target }}
          sources.zip

    - name: "Create Release"
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.web-ext-build.outputs.target }}
          sources.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}